// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Schedule
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CE Sections")]
    public partial class CESectionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CESections.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CE Sections", "In order to manage the course schedule\nAs a scheduler\nI want to manage sections", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a CE section without a topic code")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CreateACESectionWithoutATopicCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a CE section without a topic code", new string[] {
                        "domain"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 9
 testRunner.And("I have changed the approval number to 1234567890");
#line 10
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 11
 testRunner.When("I create section 01 from the course with term CE211Q1");
#line 12
 testRunner.Then("the section\'s rubric is AGEQ");
#line 13
 testRunner.And("the section\'s course number is 1091");
#line 14
 testRunner.And("the section\'s section number is 01");
#line 15
 testRunner.And("the section\'s term is CE211Q1");
#line 16
 testRunner.And("the section\'s start date is not set");
#line 17
 testRunner.And("the section\'s end date is not set");
#line 18
 testRunner.And("the section\'s title is \"Routine Management of Equine H\"");
#line 19
 testRunner.And("the section\'s credit type is Workforce Funded");
#line 20
 testRunner.And("the section\'s course type is CWECM");
#line 21
 testRunner.And("the section\'s current course type is CWECM");
#line 22
 testRunner.And("the section\'s approval number is 1234567890");
#line 23
 testRunner.And("the section\'s CIP is 123456");
#line 24
 testRunner.And("the section\'s status is pending");
#line 25
 testRunner.And("the location is blank");
#line 26
 testRunner.And("the section\'s CEUs is 0");
#line 27
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a CE section with a topic code")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CreateACESectionWithATopicCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a CE section with a topic code", new string[] {
                        "domain"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 32
 testRunner.And("I have changed the approval number to 1234567890");
#line 33
 testRunner.And("I have created a topic code BANK Banking/Finance");
#line 34
 testRunner.And("I have changed the course\'s topic code to BANK Banking/Finance");
#line 35
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 36
 testRunner.When("I create section 01 from the course with term CE211Q1");
#line 37
 testRunner.Then("the section\'s topic code is BANK");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a CE section from a special interests course without an approval or CI" +
            "P")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CanCreateACESectionFromASpecialInterestsCourseWithoutAnApprovalOrCIP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a CE section from a special interests course without an approval or CI" +
                    "P", new string[] {
                        "domain"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("I have created a Special Interests course AGEQ 1091 \"Routine Management of Equine" +
                    " Health\"");
#line 42
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 43
 testRunner.When("I create section 01 from the course with term CE211Q1");
#line 44
 testRunner.Then("the section is created");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cant create a CE section from a non-special interests course without an approval " +
            "or CIP")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CantCreateACESectionFromANon_SpecialInterestsCourseWithoutAnApprovalOrCIP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cant create a CE section from a non-special interests course without an approval " +
                    "or CIP", new string[] {
                        "domain"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 49
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 50
 testRunner.When("I create section 01 from the course with term CE211Q1");
#line 51
 testRunner.Then("the aggregate state is invalid");
#line 52
 testRunner.And("the error is \"Your attempt to create a section failed. The course doesn\'t have an" +
                    " approval number or CIP, and it\'s not a special interests course.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section number")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section number", new string[] {
                        "domain"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 56
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 57
 testRunner.And("I have changed the approval number to 1234567890");
#line 58
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 59
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 60
 testRunner.When("I change the section number to 02");
#line 61
 testRunner.Then("the section number is 02");
#line 62
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section number when the section number is taken")]
        [NUnit.Framework.CategoryAttribute("domain")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void ChangeTheSectionNumberWhenTheSectionNumberIsTaken()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section number when the section number is taken", new string[] {
                        "domain",
                        "ignore"});
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 67
 testRunner.And("I have changed the approval number to 1234567890");
#line 68
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 69
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 70
 testRunner.And("I have created a section 02 from the course with term CE211Q1");
#line 71
 testRunner.When("I change the section number to 02");
#line 72
 testRunner.Then("the command is invalid");
#line 73
 testRunner.And("the error is \"Your attempt to create a section failed. That section number is alr" +
                    "eady used.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section term")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionTerm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section term", new string[] {
                        "domain"});
#line 76
this.ScenarioSetup(scenarioInfo);
#line 77
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 78
 testRunner.And("I have changed the approval number to 1234567890");
#line 79
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 80
 testRunner.And("I have created a term CE211Q2 CE Q2 2011 from 12/1/2011 to 2/28/2012");
#line 81
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 82
 testRunner.When("I change the section\'s term to CE211Q2");
#line 83
 testRunner.Then("the section\'s term is CE211Q2");
#line 84
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section term when the section number is taken")]
        [NUnit.Framework.CategoryAttribute("domain")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void ChangeTheSectionTermWhenTheSectionNumberIsTaken()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section term when the section number is taken", new string[] {
                        "domain",
                        "ignore"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line 88
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 89
 testRunner.And("I have changed the approval number to 1234567890");
#line 90
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 91
 testRunner.And("I have created a term CE211Q2 CE Q2 2011 from 12/1/2011 to 2/28/2012");
#line 92
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 93
 testRunner.And("I have created a section 01 from the course with term CE211Q2");
#line 94
 testRunner.When("I change the section\'s term to CE211Q2");
#line 95
 testRunner.Then("the command is invalid");
#line 96
 testRunner.And("the error is \"Your attempt to create a section failed. That section number is alr" +
                    "eady used.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When changing the section term, an active section should be made pending")]
        [NUnit.Framework.CategoryAttribute("domain")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void WhenChangingTheSectionTermAnActiveSectionShouldBeMadePending()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When changing the section term, an active section should be made pending", new string[] {
                        "domain",
                        "ignore"});
#line 99
this.ScenarioSetup(scenarioInfo);
#line 100
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 101
 testRunner.And("I have changed the approval number to 1234567890");
#line 102
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 103
 testRunner.And("I have created a term CE211Q2 CE Q2 2011 from 12/1/2011 to 2/28/2012");
#line 104
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 105
 testRunner.And("I have activated the section");
#line 106
 testRunner.When("I change the section\'s term to CE211Q2");
#line 107
 testRunner.Then("the section\'s term is CE211Q2");
#line 108
 testRunner.And("the section\'s start date is blank");
#line 109
 testRunner.And("the section\'s end date is blank");
#line 110
 testRunner.And("the section\'s status is pending");
#line 111
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When changing the section term, if the section has dates, remove them")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void WhenChangingTheSectionTermIfTheSectionHasDatesRemoveThem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When changing the section term, if the section has dates, remove them", new string[] {
                        "domain"});
#line 114
this.ScenarioSetup(scenarioInfo);
#line 115
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 116
 testRunner.And("I have changed the approval number to 1234567890");
#line 117
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 118
 testRunner.And("I have created a term CE211Q2 CE Q2 2011 from 12/1/2011 to 2/28/2012");
#line 119
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 120
 testRunner.And("I have changed the section start date to 10/1/2011 and the end date to 11/1/2011");
#line 121
 testRunner.When("I change the section\'s term to CE211Q2");
#line 122
 testRunner.Then("the section\'s term is CE211Q2");
#line 123
 testRunner.And("the section\'s start date is blank");
#line 124
 testRunner.And("the section\'s end date is blank");
#line 125
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section dates")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionDates()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section dates", new string[] {
                        "domain"});
#line 130
this.ScenarioSetup(scenarioInfo);
#line 131
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 132
 testRunner.And("I have changed the approval number to 1234567890");
#line 133
 testRunner.And("I have changed the approval number to 1234567890");
#line 134
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 135
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 136
 testRunner.When("I change the start date to 10/1/2011 and the end date to 11/1/2011");
#line 137
 testRunner.Then("the section start date is 10/1/2011");
#line 138
 testRunner.And("the section end date is 11/1/2011");
#line 139
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section dates where the section dates are before the term")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionDatesWhereTheSectionDatesAreBeforeTheTerm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section dates where the section dates are before the term", new string[] {
                        "domain"});
#line 142
this.ScenarioSetup(scenarioInfo);
#line 143
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 144
 testRunner.And("I have changed the approval number to 1234567890");
#line 145
 testRunner.And("I have changed the approval number to 1234567890");
#line 146
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 147
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 148
 testRunner.When("I change the start date to 7/1/2011 and the end date to 8/1/2011");
#line 149
 testRunner.Then("the aggregate state is invalid");
#line 150
 testRunner.And("the error is \"Your attempt to create a section failed. The section census date is" +
                    " outside the term dates.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section dates where the section dates are after the term")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionDatesWhereTheSectionDatesAreAfterTheTerm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section dates where the section dates are after the term", new string[] {
                        "domain"});
#line 153
this.ScenarioSetup(scenarioInfo);
#line 154
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 155
 testRunner.And("I have changed the approval number to 1234567890");
#line 156
 testRunner.And("I have changed the approval number to 1234567890");
#line 157
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 158
 testRunner.And("I have created a section 01 from the course with term CE211Q1");
#line 159
 testRunner.When("I change the start date to 12/1/2011 and the end date to 12/25/2011");
#line 160
 testRunner.Then("the aggregate state is invalid");
#line 161
 testRunner.And("the error is \"Your attempt to create a section failed. The section census date is" +
                    " outside the term dates.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section location")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionLocation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section location", new string[] {
                        "domain"});
#line 164
this.ScenarioSetup(scenarioInfo);
#line 165
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 166
 testRunner.And("I have changed the approval number to 1234567890");
#line 167
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 168
 testRunner.And("I have created a section 01 from the course and term");
#line 169
 testRunner.And("I have created the location ACC Main Campus");
#line 170
 testRunner.When("I change the section location to ACC");
#line 171
 testRunner.Then("the section location is ACC");
#line 172
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section location to the same location")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionLocationToTheSameLocation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section location to the same location", new string[] {
                        "domain"});
#line 175
this.ScenarioSetup(scenarioInfo);
#line 176
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 177
 testRunner.And("I have changed the approval number to 1234567890");
#line 178
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 179
 testRunner.And("I have created a section 01 from the course and term");
#line 180
 testRunner.And("I have created the location ACC Main Campus");
#line 181
 testRunner.And("I have set the section location to ACC Main Campus");
#line 182
 testRunner.When("I change the section location to ACC");
#line 183
 testRunner.Then("it should do nothing");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Changing the location of a CE section to a TDCJ location doesn\'t change the topic" +
            " code")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangingTheLocationOfACESectionToATDCJLocationDoesnTChangeTheTopicCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Changing the location of a CE section to a TDCJ location doesn\'t change the topic" +
                    " code", new string[] {
                        "domain"});
#line 186
this.ScenarioSetup(scenarioInfo);
#line 187
 testRunner.Given("I have created a Workforce Non-Funded course AGEQ 1091 \"Routine Management of Equ" +
                    "ine Health\"");
#line 188
 testRunner.And("I have changed the approval number to 1234567890");
#line 189
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 190
 testRunner.And("I have created the topic code A Academic TDC Course Code");
#line 191
 testRunner.And("I have created the location CLEM Clemson Unit");
#line 192
 testRunner.And("I have created a section 01 from the course and term");
#line 193
 testRunner.When("I change the section\'s location to CLEM");
#line 194
 testRunner.Then("the section\'s location should be CLEM");
#line 195
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section credit type to non-funded")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionCreditTypeToNon_Funded()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section credit type to non-funded", new string[] {
                        "domain"});
#line 199
this.ScenarioSetup(scenarioInfo);
#line 200
 testRunner.Given("I have created a Workforce Funded course AGEQ 1091 \"Routine Management of Equine " +
                    "Health\"");
#line 201
 testRunner.And("I have changed the approval number to 1234567890");
#line 202
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 203
 testRunner.And("I have created a section 01 from the course and term");
#line 204
 testRunner.When("I change the section credit type to Workforce Non-Funded");
#line 205
 testRunner.Then("the section credit type should be Workforce Non-Funded");
#line 206
 testRunner.And("the course type CE is added to the section");
#line 207
 testRunner.And("the course type CWECM is removed from the section");
#line 208
 testRunner.And("the section\'s current course type is CE");
#line 209
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section credit type to funded")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionCreditTypeToFunded()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section credit type to funded", new string[] {
                        "domain"});
#line 212
this.ScenarioSetup(scenarioInfo);
#line 213
 testRunner.Given("I have created a Workforce Non-Funded course AGEQ 1091 \"Routine Management of Equ" +
                    "ine Health\"");
#line 214
 testRunner.And("I have changed the approval number to 1234567890");
#line 215
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 216
 testRunner.And("I have created a section 01 from the course and term");
#line 217
 testRunner.When("I change the section credit type to Workforce Funded");
#line 218
 testRunner.Then("the section credit type should be Workforce Funded");
#line 219
 testRunner.And("the course type CWECM is added to the section");
#line 220
 testRunner.And("the course type CE is removed from the section");
#line 221
 testRunner.And("the section\'s current course type is CWECM");
#line 222
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section\'s CEUs")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionSCEUs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section\'s CEUs", new string[] {
                        "domain"});
#line 225
this.ScenarioSetup(scenarioInfo);
#line 226
 testRunner.Given("I have created a Workforce Non-Funded course AGEQ 1091 \"Routine Management of Equ" +
                    "ine Health\"");
#line 227
 testRunner.And("I have changed the approval number to 1234567890");
#line 228
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 229
 testRunner.And("I have created a section 01 from the course and term");
#line 230
 testRunner.When("I change the section\'s CEUs to 0.70");
#line 231
 testRunner.Then("the section\'s CEUs is 0.70");
#line 232
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the section\'s title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheSectionSTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the section\'s title", new string[] {
                        "domain"});
#line 235
this.ScenarioSetup(scenarioInfo);
#line 236
 testRunner.Given("I have created a Workforce Non-Funded course AGEQ 1091 \"Routine Management of Equ" +
                    "ine Health\"");
#line 237
 testRunner.And("I have changed the approval number to 1234567890");
#line 238
 testRunner.And("I have created a term CE211Q1 CE Q1 2011 from 9/1/2011 to 11/30/2011");
#line 239
 testRunner.And("I have created a section 01 from the course and term");
#line 240
 testRunner.When("I change the section\'s title to \"Horses\"");
#line 241
 testRunner.Then("the section\'s title is \"Horses\"");
#line 242
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
