// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Schedule
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Manage course title, long title, and description")]
    public partial class ManageCourseTitleLongTitleAndDescriptionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CourseTitleAndDescription.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Manage course title, long title, and description", "In order to manage the course schedule\nAs a scheduler\nI want to change the course" +
                    " title, long title, and description", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a credit course with a very long title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CreateACreditCourseWithAVeryLongTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a credit course with a very long title", new string[] {
                        "domain"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.When("I create an ACAD course BIOL 1301 Very Very Very Very Long Title For Introductory" +
                    " Biology");
#line 9
 testRunner.Then("the course title is Very Very Very Very Long Title");
#line 10
 testRunner.And("the course long title is Very Very Very Very Long Title For Introductory Biology");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change course title when long title matches title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeCourseTitleWhenLongTitleMatchesTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change course title when long title matches title", new string[] {
                        "domain"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 15
 testRunner.When("I change the course title to Biology 101");
#line 16
 testRunner.Then("the course title is Biology 101");
#line 17
 testRunner.And("the course long title is Biology 101");
#line 18
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change course title when long title doesn\'t match title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeCourseTitleWhenLongTitleDoesnTMatchTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change course title when long title doesn\'t match title", new string[] {
                        "domain"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 23
 testRunner.And("the course long title is Very Very Very Very Long Title For Introductory Biology");
#line 24
 testRunner.When("I change the course title to Biology 101");
#line 25
 testRunner.Then("the course title is Biology 101");
#line 26
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change course long title when long title matches title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeCourseLongTitleWhenLongTitleMatchesTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change course long title when long title matches title", new string[] {
                        "domain"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 31
 testRunner.When("I change the course long title to Long title of Introductory Biology");
#line 32
 testRunner.Then("the course long title is Long title of Introductory Biology");
#line 33
 testRunner.And("the course title is Long title of Introductory Bio");
#line 34
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change course long title when long title doesn\'t match title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeCourseLongTitleWhenLongTitleDoesnTMatchTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change course long title when long title doesn\'t match title", new string[] {
                        "domain"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 39
 testRunner.When("I change the course long title to Long title of Introductory Biology");
#line 40
 testRunner.Then("the course long title is Long title of Introductory Biology");
#line 41
 testRunner.And("the course title is Long title of Introductory Bio");
#line 42
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change course description")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeCourseDescription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change course description", new string[] {
                        "domain"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 47
 testRunner.When("I change the course description to Cutting up frogs");
#line 48
 testRunner.Then("the course description is Cutting up frogs");
#line 49
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Set course description to the same description")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void SetCourseDescriptionToTheSameDescription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set course description to the same description", new string[] {
                        "domain"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 54
 testRunner.And("I have changed the course description to Cutting up frogs");
#line 55
 testRunner.When("I change the course description to Cutting up frogs");
#line 56
 testRunner.Then("it should do nothing");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Set course title to the same title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void SetCourseTitleToTheSameTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set course title to the same title", new string[] {
                        "domain"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 61
 testRunner.When("I change the course title to Introductory Biology");
#line 62
 testRunner.Then("it should do nothing");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Set course long title to the same long title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void SetCourseLongTitleToTheSameLongTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set course long title to the same long title", new string[] {
                        "domain"});
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("I have created an ACAD course BIOL 1301 Introductory Biology");
#line 67
 testRunner.And("I have set the course long title to Long title of Introductory Biology");
#line 68
 testRunner.When("I change the course long title to Long title of Introductory Biology");
#line 69
 testRunner.Then("it should do nothing");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
