// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Schedule
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Credit Sections")]
    public partial class CreditSectionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreditSections.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Credit Sections", "In order to manage the course schedule\nAs a scheduler\nI want to manage sections", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location")]
        [NUnit.Framework.CategoryAttribute("domain:")]
        public virtual void ChangeTheCreditSectionLocation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location", new string[] {
                        "domain:"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 9
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 10
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 11
 testRunner.And("I have created a section 01 from the course and term");
#line 12
 testRunner.And("I have created a location ACC Main Campus");
#line 13
 testRunner.When("I change the section location to ACC");
#line 14
 testRunner.Then("the section location is ACC");
#line 15
 testRunner.And("the section location abbreviation is ACC");
#line 16
 testRunner.And("the section location name is Main Campus");
#line 17
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to CLEM")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToCLEM()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to CLEM", new string[] {
                        "domain"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 22
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 23
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 24
 testRunner.And("I have created a section 01 from the course and term");
#line 25
 testRunner.And("I have created a location CLEM Clemens Unit");
#line 26
 testRunner.When("I change the section location to CLEM");
#line 27
 testRunner.Then("the section location is CLEM");
#line 28
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 29
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location from TDCJ back to non-TDCJ")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationFromTDCJBackToNon_TDCJ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location from TDCJ back to non-TDCJ", new string[] {
                        "domain"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 34
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 35
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 36
 testRunner.And("I have created a section 01 from the course and term");
#line 37
 testRunner.And("I have created a location CLEM Clemens Unit");
#line 38
 testRunner.And("I have created a location ACC Main Campus");
#line 39
 testRunner.And("I have set the section location to CLEM Clemens Unit");
#line 40
 testRunner.When("I change the section location to ACC");
#line 41
 testRunner.Then("the section location is ACC");
#line 42
 testRunner.And("the topic code is blank");
#line 43
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location from one TDCJ to another")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationFromOneTDCJToAnother()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location from one TDCJ to another", new string[] {
                        "domain"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 48
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 49
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 50
 testRunner.And("I have created a section 01 from the course and term");
#line 51
 testRunner.And("I have created a location CLEM Clemens Unit");
#line 52
 testRunner.And("I have created a location DAR Darrington Unit");
#line 53
 testRunner.And("I have set the section location to CLEM Clemens Unit");
#line 54
 testRunner.When("I change the section location to DAR");
#line 55
 testRunner.Then("the section location is DAR");
#line 56
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location from one non-TDCJ to another")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationFromOneNon_TDCJToAnother()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location from one non-TDCJ to another", new string[] {
                        "domain"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 61
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 62
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 63
 testRunner.And("I have created a section 01 from the course and term");
#line 64
 testRunner.And("I have created a location ACC Main Campus");
#line 65
 testRunner.And("I have created a location AHS Alvin High School");
#line 66
 testRunner.And("I have set the section location to ACC Main Campus");
#line 67
 testRunner.When("I change the section location to AHS");
#line 68
 testRunner.Then("the section location is AHS");
#line 69
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to CV")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToCV()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to CV", new string[] {
                        "domain"});
#line 72
this.ScenarioSetup(scenarioInfo);
#line 73
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 74
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 75
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 76
 testRunner.And("I have created a section 01 from the course and term");
#line 77
 testRunner.And("I have created a location CV Carol Vance");
#line 78
 testRunner.When("I change the section location to CV");
#line 79
 testRunner.Then("the section location is CV");
#line 80
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 81
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to DAR")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToDAR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to DAR", new string[] {
                        "domain"});
#line 84
this.ScenarioSetup(scenarioInfo);
#line 85
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 86
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 87
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 88
 testRunner.And("I have created a section 01 from the course and term");
#line 89
 testRunner.And("I have created a location DAR Darrington Unit");
#line 90
 testRunner.When("I change the section location to DAR");
#line 91
 testRunner.Then("the section location is DAR");
#line 92
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 93
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to J1")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToJ1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to J1", new string[] {
                        "domain"});
#line 96
this.ScenarioSetup(scenarioInfo);
#line 97
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 98
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 99
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 100
 testRunner.And("I have created a section 01 from the course and term");
#line 101
 testRunner.And("I have created a location J1 Jester 1 Unit");
#line 102
 testRunner.When("I change the section location to J1");
#line 103
 testRunner.Then("the section location is J1");
#line 104
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 105
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to J2")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToJ2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to J2", new string[] {
                        "domain"});
#line 108
this.ScenarioSetup(scenarioInfo);
#line 109
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 110
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 111
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 112
 testRunner.And("I have created a section 01 from the course and term");
#line 113
 testRunner.And("I have created a location J2 Jester 2 Unit");
#line 114
 testRunner.When("I change the section location to J2");
#line 115
 testRunner.Then("the section location is J2");
#line 116
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 117
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to J3")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToJ3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to J3", new string[] {
                        "domain"});
#line 120
this.ScenarioSetup(scenarioInfo);
#line 121
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 122
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 123
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 124
 testRunner.And("I have created a section 01 from the course and term");
#line 125
 testRunner.And("I have created a location J3 Jester 3 Unit");
#line 126
 testRunner.When("I change the section location to J3");
#line 127
 testRunner.Then("the section location is J3");
#line 128
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 129
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to TER")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToTER()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to TER", new string[] {
                        "domain"});
#line 132
this.ScenarioSetup(scenarioInfo);
#line 133
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 134
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 135
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 136
 testRunner.And("I have created a section 01 from the course and term");
#line 137
 testRunner.And("I have created a location TER T. C. Terrell Unit");
#line 138
 testRunner.When("I change the section location to TER");
#line 139
 testRunner.Then("the section location is TER");
#line 140
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 141
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to R1")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToR1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to R1", new string[] {
                        "domain"});
#line 144
this.ScenarioSetup(scenarioInfo);
#line 145
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 146
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 147
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 148
 testRunner.And("I have created a section 01 from the course and term");
#line 149
 testRunner.And("I have created a location R1 Ramsey 1 Unit");
#line 150
 testRunner.When("I change the section location to R1");
#line 151
 testRunner.Then("the section location is R1");
#line 152
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 153
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change the credit section location to R2")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeTheCreditSectionLocationToR2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change the credit section location to R2", new string[] {
                        "domain"});
#line 156
this.ScenarioSetup(scenarioInfo);
#line 157
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 158
 testRunner.And("I have created a topic code A Academic TDC Course Code");
#line 159
 testRunner.And("I have created a term 211FA Fall 2011 from 8/25/2011 to 12/7/2011");
#line 160
 testRunner.And("I have created a section 01 from the course and term");
#line 161
 testRunner.And("I have created a location R2 Stringfellow Unit");
#line 162
 testRunner.When("I change the section location to R2");
#line 163
 testRunner.Then("the section location is R2");
#line 164
 testRunner.And("the topic code is A Academic TDC Course Code");
#line 165
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a credit section without a topic code")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CreateACreditSectionWithoutATopicCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a credit section without a topic code", new string[] {
                        "domain"});
#line 168
this.ScenarioSetup(scenarioInfo);
#line 169
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 170
 testRunner.And("I have set the approval number to 1234567890");
#line 171
 testRunner.And("I have created a term 211FA Fall 2011 from 9/1/2011 to 11/30/2011");
#line 172
 testRunner.When("I create section 01 from the course and term");
#line 173
 testRunner.Then("the section\'s course is BIOL 1301");
#line 174
 testRunner.And("the section\'s term is 211FA");
#line 175
 testRunner.And("the section\'s rubric is BIOL");
#line 176
 testRunner.And("the section\'s course number is 1301");
#line 177
 testRunner.And("the section\'s section number is 01");
#line 178
 testRunner.And("the section\'s term abbreviation is 211FA");
#line 179
 testRunner.And("the section\'s term name is Fall 2011");
#line 180
 testRunner.And("the section\'s start date is 9/1/2011");
#line 181
 testRunner.And("the section\'s end date is 11/30/2011");
#line 182
 testRunner.And("the section\'s title is \"Introductory Biology\"");
#line 183
 testRunner.And("the section\'s course type is ACAD");
#line 184
 testRunner.And("the section\'s approval number is 1234567890");
#line 185
 testRunner.And("the section\'s CIP is 123456");
#line 186
 testRunner.And("it should do nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cant create a credit section without an approval number or CIP")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CantCreateACreditSectionWithoutAnApprovalNumberOrCIP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cant create a credit section without an approval number or CIP", new string[] {
                        "domain"});
#line 189
this.ScenarioSetup(scenarioInfo);
#line 190
 testRunner.Given("I have created an ACAD course BIOL 1301 \"Introductory Biology\"");
#line 191
 testRunner.And("I have created a term 211FA Fall 2011 from 9/1/2011 to 11/30/2011");
#line 192
 testRunner.When("I create section 01 from the course and term");
#line 193
 testRunner.Then("the aggregate state is invalid");
#line 194
 testRunner.And("the error is \"Your attempt to create the section failed. Set approval number or C" +
                    "IP at the course level first.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
